travis:
  secure:
    BINSTAR_TOKEN: oYB9w5yD0rNPczQ9gjZSh+IcO2U1TL9FbcIvyihWHu0G+Tzidh/QaG3E+1/tvNJf4ZAfnVzx62v6ac6CRfESGngP/NFStI1MlhuST6lv7FeEG+NpW/DWjI9oHYnpVTqp90aXWXO/6HD2OuX1ms6TcPO4fkTuhvakMPZpuh6HFBTmnVbkaQhrWTrlnLCYSfB1fxHndoQVJAMFCcXlCfu16RBkl8xuMV15GVy8nut1uay6/UeJI6ZZgZzy6emD72Oan8gV9tveTckxfmJrC//Gxjg1VxLXinCnye7DroGcjSMX7SXsv7c09Hz2SC6tsAPr2JsQC4K9VnaokN2gHVVoPg+TA5TzIjeRtHPd4RVprUF2guBiKUM+4piVB0DJID/A/tmlrgA4bykPECcrtdARAQOEFJebml1U33aUH+f6TfMi52ClETwVmIt0scv5OfRel5uQEe+BujlUIwUd3LO9x0y0zZ0NclWTKEdPra3VbDe+SMFsXgIacEnVLSF5SofmxoSSAdACN1/v1RZYucNt00IO6lXRX5jLa4nbwssqOe6cVvuhMfwHTr1zxknSwN85/njRuX2kwZrb7J4tHZzwXRQV3nIx32EGzUGBjof//va42H5eyw10rhVRX0vq9DhJcJ0BuO1XqA/sucvsu745Sn9jhB+UCr6QaSOyVTMw+xs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
